# Generated by Django 4.0.6 on 2023-06-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(blank=True, max_length=50, null=True)),
                ('buyprice', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sellprice', models.DecimalField(decimal_places=3, max_digits=10)),
                ('position', models.CharField(choices=[('L', 'Long'), ('S', 'Short')], max_length=1)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='journal_images/')),
            ],
        ),
    ]
