# Generated by Django 4.0.6 on 2023-06-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_journal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='buyprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='journal_images/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='position',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='journal',
            name='sellprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
