# Generated by Django 4.0.6 on 2023-06-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_buyprice_journal_entryprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='journal_images/'),
        ),
    ]
