# Generated by Django 4.0.6 on 2023-07-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_journal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
